/* Reads cloud overrides without requiring a GitHub deployment per product. */
(() => {
  if (!window.CatalogAPI?.configured) return;
  let running=false, fingerprint='', collectionFingerprint='';
  const versions=new Map();
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const womenSweaterSize=size=>size==='S/M'?'1':size==='M/L'?'2':size;
  function normalizeCatalogProduct(product){
    const memberships=Array.isArray(product.collections)&&product.collections.length?product.collections:[product.collection].filter(Boolean);
    if(memberships.includes('primavera-2027'))memberships.push('invierno-2027');
    if(memberships.some(id=>id==='sweaters-2027'||id==='hoodies-2027'))memberships.push('produccion-invierno-2027');
    product.collections=[...new Set(memberships)];
    if(product.category==='MUJER'&&product.subcategory==='Sweaters')for(const group of [product,...(product.purchaseOptions||[])]){
      group.sizes=(group.sizes||[]).map(womenSweaterSize);
      for(const row of group.packaging?.rows||[])row.sizePieces=Object.fromEntries(Object.entries(row.sizePieces||{}).map(([size,pieces])=>[womenSweaterSize(size),pieces]));
    }
  }
  function sanitize(value,key='') {
    if(Array.isArray(value))return value.map(v=>sanitize(v,key));
    if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['__proto__','constructor','prototype'].includes(k)).map(([k,v])=>[escape(k),sanitize(v,k)]));
    if(typeof value==='string') {
      if (/^\s*(javascript|data|vbscript):/i.test(value)) return ''; 
      if(/^https:\/\//.test(value)) {try{const u=new URL(value);return u.protocol==='https:'?escape(u.href):'';}catch{return '';}}
      // Relative photo paths are generated by the trusted catalog seed.
      if(/^images\/[\w.-]+\.(jpg|jpeg|png|webp)(\?v=[\w-]+)?$/.test(value))return value;
      return escape(value);
    }
    return value;
  }
  async function refresh(){
    if(running||document.hidden)return;running=true;
    try{
      let collectionChanged=false;
      try {
        const collectionRows=await CatalogAPI.listCollections(),nextCollections=JSON.stringify(collectionRows.map(r=>[r.id,r.version]));
        if(nextCollections!==collectionFingerprint){
          for(const row of collectionRows){if(!row.payload?.name||!['stock','preorder'].includes(row.payload.type))continue;const payload=sanitize(row.payload),next={...payload,id:row.id,type:row.payload.type};const index=collections.findIndex(c=>c.id===row.id);if(index<0)collections.push(next);else collections[index]=next;}
          collectionFingerprint=nextCollections;collectionChanged=true;buildCollectionFilters();
        }
      } catch(error) { console.warn('Las colecciones conservan su configuración local.',error.message); }
      const metadata=await CatalogAPI.list('id,version'),next=JSON.stringify(metadata.map(r=>[r.id,r.version]));
      if(next===fingerprint&&!collectionChanged)return;
      const changed=metadata.filter(r=>versions.get(Number(r.id))!==r.version);
      const rows=await CatalogAPI.getProducts(changed.map(r=>Number(r.id)));
      for(const row of rows){const id=Number(row.id);if(!Number.isSafeInteger(id)||!row.payload?.name)continue;
        const p=sanitize(row.payload);p.id=id;p.cloudManaged=true;p.collections=p.collections||[p.collection];p.colors=p.colors||[];p.outOfStockColors=p.outOfStockColors||[];p.sizes=p.sizes||[];p.inStock=p.inStock!==false;normalizeCatalogProduct(p);
        const groups=p.purchaseOptions?.length?p.purchaseOptions:[p];
        for(const group of groups)if(group.packaging)normalizePackagingTotals(group.packaging,group.packingType||(/POR COLOR|SOLID COLOR/i.test(group.sourcePacking||'')?'single-color':'mixed-colors'));
        const existing=products.findIndex(v=>v.id===id);if(existing<0)products.push(p);else products[existing]=p;
      }
      for(const row of rows)versions.set(Number(row.id),row.version);
      fingerprint=next;
      // Refresh open detail only when its saved version changes, preserving its option.
      const openId=currentModalProduct?.id,openBefore=currentModalProduct;
      cart=cart.map(item=>{const p=products.find(p=>p.id===item.id),cartCollection=collections.find(c=>c.id===(item.cartCollectionId||item.collection));if(!p||p.isHidden||(cartCollection&&isPreorderCollection(cartCollection)))return null;const selectedPurchaseOption=p.purchaseOptions?.find(o=>o.id===item.selectedPurchaseOption?.id)||null;if(!canOrderProduct(p,cartCollection||getActiveCollection(),selectedPurchaseOption))return null;return {...item,...p,selectedPurchaseOption};}).filter(Boolean);
      buildCategoryFilters();renderProducts();updateCartUI();persistCart();
      if(openId){const p=products.find(p=>p.id===openId);if(p?.isHidden)closeModal();else if(p&&(collectionChanged||JSON.stringify(p)!==JSON.stringify(openBefore)))openModal(p,currentPurchaseOptionId);}
    }catch(error){console.warn('El catálogo conserva su última versión disponible.',error.message);}finally{running=false;}
  }
  document.addEventListener('DOMContentLoaded',()=>{refresh();setInterval(refresh,10000);});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
  window.addEventListener('online',refresh);
})();
