/* Reads cloud overrides without requiring a GitHub deployment per product. */
(() => {
  if (!window.CatalogAPI?.configured) return;
  let running=false, fingerprint='';
  const versions=new Map();
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function sanitize(value,key='') {
    if(Array.isArray(value))return value.map(v=>sanitize(v,key));
    if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['__proto__','constructor','prototype'].includes(k)).map(([k,v])=>[escape(k),sanitize(v,k)]));
    if(typeof value==='string') {
      if (/^\s*(javascript|data|vbscript):/i.test(value)) return ''; 
      if(/^https:\/\//.test(value)) {try{const u=new URL(value);return u.protocol==='https:'?escape(u.href):'';}catch{return '';}}
      // Relative photo paths are generated by the trusted catalog seed.
      if(/^images\/[\w.-]+\.(jpg|jpeg|png|webp)(\?v=[\w-]+)?$/.test(value))return value;
      return escape(value);
    }
    return value;
  }
  async function refresh(){
    if(running||document.hidden)return;running=true;
    try{
      const metadata=await CatalogAPI.list('id,version'),next=JSON.stringify(metadata.map(r=>[r.id,r.version]));if(next===fingerprint)return;
      const changed=metadata.filter(r=>versions.get(Number(r.id))!==r.version);
      const rows=await CatalogAPI.getProducts(changed.map(r=>Number(r.id)));
      for(const row of rows){const id=Number(row.id);if(!Number.isSafeInteger(id)||!row.payload?.name)continue;
        const p=sanitize(row.payload);p.id=id;p.cloudManaged=true;p.collections=p.collections||[p.collection];p.colors=p.colors||[];p.sizes=p.sizes||[];p.inStock=p.inStock!==false;
        const existing=products.findIndex(v=>v.id===id);if(existing<0)products.push(p);else products[existing]=p;
      }
      for(const row of rows)versions.set(Number(row.id),row.version);
      fingerprint=next;
      // Refresh open detail only when its saved version changes, preserving its option.
      const openId=currentModalProduct?.id,openBefore=currentModalProduct;
      cart=cart.map(item=>{const p=products.find(p=>p.id===item.id);if(!p||!p.inStock||p.isHidden)return null;const selectedPurchaseOption=p.purchaseOptions?.find(o=>o.id===item.selectedPurchaseOption?.id)||null;return {...item,...p,selectedPurchaseOption};}).filter(Boolean);
      buildCategoryFilters();renderProducts();updateCartUI();persistCart();
      if(openId){const p=products.find(p=>p.id===openId);if(p?.isHidden)closeModal();else if(p&&JSON.stringify(p)!==JSON.stringify(openBefore))openModal(p,currentPurchaseOptionId);}
    }catch(error){console.warn('El catálogo conserva su última versión disponible.',error.message);}finally{running=false;}
  }
  document.addEventListener('DOMContentLoaded',()=>{refresh();setInterval(refresh,10000);});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
  window.addEventListener('online',refresh);
})();
