-- Run once in the SQL Editor of the NEW catalog project.
-- Product contents are public; editor membership and writes are private.
create table if not exists public.catalog_editors (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.catalog_editors enable row level security;
create policy "Editors see own membership" on public.catalog_editors
  for select to authenticated using (user_id = (select auth.uid()));
revoke all on public.catalog_editors from anon, authenticated;
grant select on public.catalog_editors to authenticated;

create table if not exists public.catalog_products (
  id bigint generated by default as identity (start with 10000) primary key,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  version integer not null default 1,
  updated_at timestamptz not null default now()
);
alter table public.catalog_products enable row level security;
create policy "Public catalog read" on public.catalog_products for select to anon, authenticated using (true);
revoke all on public.catalog_products from anon, authenticated;
grant select on public.catalog_products to anon, authenticated;

create or replace function public.save_catalog_product(product_id bigint, expected_version integer, product_data jsonb)
returns public.catalog_products language plpgsql security definer set search_path = '' as $$
declare result public.catalog_products;
begin
  if not exists(select 1 from public.catalog_editors where user_id = auth.uid()) then
    raise insufficient_privilege using message = 'EDITOR_REQUIRED';
  end if;
  if jsonb_typeof(product_data) <> 'object' or length(trim(coalesce(product_data->>'name',''))) = 0
     or length(product_data::text) > 500000
     or jsonb_typeof(product_data->'colors') is distinct from 'array'
     or jsonb_typeof(product_data->'sizes') is distinct from 'array' then
    raise exception 'INVALID_PRODUCT';
  end if;
  if product_id is null then
    insert into public.catalog_products(payload) values(product_data) returning * into result;
  elsif expected_version = 0 then
    if product_id < 1 or product_id >= 10000 then raise exception 'INVALID_LEGACY_ID'; end if;
    insert into public.catalog_products(id,payload) values(product_id,product_data)
    on conflict (id) do nothing returning * into result;
    if result.id is null then raise exception 'EDIT_CONFLICT'; end if;
  else
    update public.catalog_products set payload = product_data, version = version + 1, updated_at = now()
    where id = product_id and version = expected_version returning * into result;
    if result.id is null then raise exception 'EDIT_CONFLICT'; end if;
  end if;
  return result;
end;
$$;
revoke all on function public.save_catalog_product(bigint,integer,jsonb) from public;
grant execute on function public.save_catalog_product(bigint,integer,jsonb) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('catalog-photos','catalog-photos',true,5242880,array['image/webp']) on conflict (id) do nothing;
create policy "Editors upload catalog photos" on storage.objects for insert to authenticated
with check (bucket_id = 'catalog-photos' and (storage.foldername(name))[1] = auth.uid()::text
  and exists(select 1 from public.catalog_editors where user_id = auth.uid()));
-- No public writes, no file overwrite, no deletion through the panel.
-- After creating the two Auth users, authorize their exact IDs:
-- insert into public.catalog_editors(user_id) values ('USER_UUID_1'), ('USER_UUID_2');
