const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function apiWith(fetch,session){const storage=new Map();if(session)storage.set('byebye-admin-session',JSON.stringify(session));const context={window:{CATALOG_CONFIG:{url:'https://test.supabase.co',publicKey:'sb_publishable_test'}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch,AbortSignal,Date,JSON,crypto:require('node:crypto').webcrypto};vm.runInNewContext(fs.readFileSync('catalog-api.js','utf8'),context);return context.window.CatalogAPI;}
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data,text:async()=>JSON.stringify(data)});
const session={user:{id:'test-user'},access_token:'test-access',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600};
test('anonymous catalog reads do not transmit an editor session',async()=>{const api=apiWith(async(url,opts)=>{assert(!opts.headers.Authorization);return response([]);},session);assert.equal((await api.list()).length,0);});
test('unauthenticated saves never call the backend',async()=>{let called=false;const api=apiWith(async()=>{called=true});await assert.rejects(api.save(null,0,{}),/Ingresá/);assert.equal(called,false);});
test('save passes expected version and surfaces conflict without retry or overwrite',async()=>{let calls=0;const api=apiWith(async(url,opts)=>{calls++;assert.equal(JSON.parse(opts.body).expected_version,2);return response({message:'EDIT_CONFLICT'},400)},session);await assert.rejects(api.save(262,2,{name:'Example'}),/Tu socia/);assert.equal(calls,1);});
test('editor membership required after successful login',async()=>{const api=apiWith(async url=>url.includes('/token')?response(session):response([]));await assert.rejects(api.login('test@example.com','fake-test-password'),/no está habilitada/);assert.equal(api.user,null);});
test('expired session refreshes before authenticated save',async()=>{const paths=[];const api=apiWith(async(url,opts)=>{paths.push(url);if(url.includes('/token'))return response(session);assert.equal(opts.headers.Authorization,'Bearer test-access');return response({id:10000,version:1});},{...session,expires_at:0});const result=await api.save(null,0,{name:'Example'});assert.equal(result.id,10000);assert(paths[0].includes('refresh_token'));assert.equal(paths.length,2);});
